# Generated by Django 5.1.6 on 2025-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
